### ISSUE TITLE
disable when in private mode

### ISSUE THREAD

**Issue by girst** [stoically/firefox-add-on-temporary-containers#8] opened 2017-11-30 21:06 UTC
In private mode containers don't work (not only temp-containers, but multiple containers as well). 

it does however create an entry in the container-list, which has to be manually deleted then.

maybe the icon could be greyed out (like multiple-containers) and the context menu entry removed?

--

I don't think this is very major, and might just be left as-is, but I wanted to mention it for completeness. ;-)      
as always, thanks for providing this addon and... wow -  you are churning out updates faster than i can keep downloading them!

**Comment by stoically** [comment] 2017-11-30 23:31
Hey! Nice catch, yeah, I'll look into disabling Icon and Context Menu in Private Windows. However, you don't really need to remove the container manually, it will be removed automatically by the 60s cleanup interval (which exists because sometimes Firefox is still reporting tabs to exist in containers despite the fact that all tabs have already been closed).

You're welcome and I'm happy you like it! :)

**Comment by stoically** [comment] 2017-12-02 00:31
Just published version 0.14 with the bugfix. Thanks for reporting!

**Comment by stoically** [comment] 2017-12-02 00:35
Well, I forgot about that ContextMenu Entry again. I guess it's not done yet.

**Comment by stoically** [comment] 2017-12-02 05:22
Published version 0.15 - now it's fixed.

**Comment by prog-amateur** [comment] 2018-01-24 09:18
Hello, thank you very much for your web extension. You said that the issue is closed, but I still have the same problem in private mode, could you please check ? 
Thank you very much !

**Comment by stoically** [comment] 2018-01-24 13:20
@prog-amateur Hi, glad you like it. What exactly doesn't work for you? Please keep in mind that this issue was about disabling Temporary Containers buttons since Firefox doesn't support container in Private Mode at all.

**Comment by stoically** [comment] 2018-01-24 13:34
Just upgraded to Firefox58 and the bug is indeed back. Looking into it, thanks for letting me know.

**Comment by stoically** [comment] 2018-01-25 13:44
Fixed with just published version 0.20

**Closed by stoically** 2018-01-25 13:44 UTC
Labels: bug, enhancement
